### ISSUE TITLE
Error: Activity has leaked IntentReceiver

### ISSUE THREAD

**Issue by palicka** [andrefio/Rx.Network#1]
In Activity's _onCreate()_ I call:
```
        connectivityManager = getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
        RxNetwork.connectivityChanges(this, connectivityManager)
                .subscribe({ connected: Boolean -> if (connected) refreshApp() })
```

when I press back button this error shows up:

```
Activity com.mypackage.MainActivity has leaked IntentReceiver io.andref.rx.content.OnSubscribeBroadcastRegister$1@c58a89f that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                     android.app.IntentReceiverLeaked: Activity com.mypackage.MainActivity has leaked IntentReceiver io.andref.rx.content.OnSubscribeBroadcastRegister$1@c58a89f that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                         at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1030)
                                                                         at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:817)
                                                                         at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1256)
                                                                         at android.app.ContextImpl.registerReceiver(ContextImpl.java:1236)
                                                                         at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:583)
                                                                         at io.andref.rx.content.OnSubscribeBroadcastRegister.call(OnSubscribeBroadcastRegister.java:65)
                                                                         at io.andref.rx.content.OnSubscribeBroadcastRegister.call(OnSubscribeBroadcastRegister.java:28)
                                                                         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                                                         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                                                         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                         at rx.Observable.subscribe(Observable.java:8759)
                                                                         at rx.Observable.subscribe(Observable.java:8726)
                                                                         at rx.Observable.subscribe(Observable.java:8549)
                                                                         at com.mypackage.MainActivity.onCreate(MainActivity.kt:52)

```

It looks like, it comes from OnSubscribeBroadcastRegister's method call()

Thanks

**Comment by mukeshsolanki** [comment]
I have the same issue. Maybe you need to release the subscriber to fix this issue
